query Ecritures ($where: JSON!) {
  ecritures (where: $where) {
    id, name, description, priority, slug,
    image { id, formats },
    realisations { id, title,
      images { formats }
    }
  }
}